version: '3.8'

services:
  db:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - e-commerce-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - e-commerce-network
    env_file:
      - .env

networks:
  e-commerce-network:
    driver: bridge

volumes:
  pg-data:
